name: Deploy to Hugging Face Space

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Git (with LFS)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git lfs install

      - name: Add HF remote
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          HF_SPACE_URL="https://huggingface.co/spaces/lee038/LyricsTranslation"
          HF_PUSH_URL="https://user:${HF_TOKEN}@huggingface.co/spaces/lee038/LyricsTranslation"
          git remote remove hf 2>/dev/null || true
          git remote add hf "$HF_SPACE_URL"
          git remote set-url --push hf "$HF_PUSH_URL"
          git remote -v

      - name: Push to HF Space (main)
        run: |
          git push hf main:main --follow-tags --force-with-lease
